#ifndef  __HI_COMMON_API_H__
#define  __HI_COMMON_API_H__

#include <hi_comm_adec.h>
#include <hi_comm_aenc.h>
#include <hi_comm_ai.h>
#include <hi_comm_aio.h>
#include <hi_comm_ao.h>
#include <hi_comm_avenc.h>
#include <hi_comm_dwm.h>
#include <hi_comm_group.h>
#include <hi_comm_md.h>
#include <hi_comm_sys.h>
#include <hi_comm_vb.h>
#include <hi_comm_vdec.h>
#include <hi_comm_venc.h>
#include <hi_comm_vi.h>
#include <hi_comm_video.h>
#include <hi_comm_vo.h>
#include <hi_comm_vpp.h>
#include <hi_common.h>
#include <hi_debug.h>
#include <hi_errno.h>
#include <hi_type.h>
#include <hifb.h>
#include <loadbmp.h>
#include <mpi_adec.h>
#include <mpi_aenc.h>
#include <mpi_ai.h>
#include <mpi_ao.h>
#include <mpi_avenc.h>
#include <mpi_md.h>
#include <mpi_sys.h>
#include <mpi_vb.h>
#include <mpi_vdec.h>
#include <mpi_venc.h>
#include <mpi_vi.h>
#include <mpi_vo.h>
#include <mpi_vpp.h>
#include <tde_debug.h>
#include <tde_interface.h>

#endif 
